[Container]
Memory=7g
PidsLimit=8192
StopTimeout=190
CgroupConf=memory.swap.max=0
CgroupConf=memory.high=6300000000
CgroupConf=memory.oom.group=1

[Service]
MemoryHigh=6300m
MemorySwapMax=0
TimeoutStopSec=220
TimeoutStartSec=900
CPUWeight=200
